openapi: 3.0.3
info:
  title: API
  description: An API for managing PA licensing platform
  version: 0.1.0
  contact:
    name: Focus Consulting

servers:
  - url: /v1

tags:
  - name: Health

paths:
  /health:
    get:
      summary: Health Check for the API
      tags:
        - Health
      operationId: licensing_api.controllers.health
      responses:
        "200":
          $ref: "#/components/responses/HealthResponse"

  /health/deep:
    get:
      summary: More extensive health check for the API
      tags:
        - Health
      operationId: licensing_api.controllers.health_deep
      responses:
        "200":
          $ref: "#/components/responses/HealthResponseDeep"

components:
  #
  # RESPONSES
  #
  responses:
    HealthResponse:
      description: Status check that the API is
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/SuccessfulResponse"
              - properties:
                  data:
                    type: object
                    required:
                      - status
                      - timestamp
                      - apiName
                      - apiVersion
                    properties:
                      status:
                        type: string
                        example: up
                        nullable: false
                      timestamp:
                        type: string
                        format: date-time
                        nullable: false
                        example: "2023-06-26T01:02:03.967736+00:00"
                      apiName:
                        type: string
                        nullable: false
                        example: api
                      apiVersion:
                        type: string
                        nullable: false
                        example: v1

    HealthResponseDeep:
      description: Validates that the API is available and connected to the database
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/SuccessfulResponse"
              - properties:
                  data:
                    type: object
                    required:
                      - status
                      - timestamp
                      - apiName
                      - apiVersion
                      - components
                    properties:
                      status:
                        type: string
                        example: up
                        nullable: false
                      timestamp:
                        type: string
                        format: date-time
                        nullable: false
                        example: "2023-06-26T01:02:03.967736+00:00"
                      apiName:
                        type: string
                        nullable: false
                        example: api
                      apiVersion:
                        type: string
                        nullable: false
                        example: v1
                      components:
                        type: object
                        properties:
                          db:
                            type: object
                            properties:
                              status:
                                type: string
                                example: up

    BadRequest:
      description: There was a problem with your request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  #
  # SCHEMAS
  #
  schemas:
    SuccessfulResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 200
        message:
          type: string
          example: "Success"
        meta:
          $ref: "#/components/schemas/Meta"
        data:
          oneOf:
            - type: array
              items: {}
            - type: object
          example: []
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
          example: []
      required: ["statusCode"]
      additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
        message:
          type: string
        meta:
          $ref: "#/components/schemas/Meta"
        data:
          oneOf:
            - type: array
              items: {}
            - type: object
          example: []
        warnings:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationErrorDetail"
      required: ["statusCode", "errors"]
      additionalProperties: false

    Meta:
      type: object
      properties:
        resource:
          type: string
          example: "/v1"
        method:
          type: string
          example: "GET"
        query:
          type: object
          nullable: true
        paging:
          type: object
          nullable: true
          properties:
            pageOffset:
              type: integer
            pageSize:
              type: integer
            totalRecords:
              type: integer
            totalPages:
              type: integer
            orderBy:
              type: string
            orderDirection:
              type: string
      required: ["method", "resource"]
      additionalProperties: false

    ValidationErrorDetail:
      type: object
      properties:
        errorType:
          type: string
          example: "required"
        message:
          example: "applicant.dob is required."
          description: "Somewhat user-friendly description of the error. May contain PII."
          type: string
        rule:
          description: >
            Usage varies depending on the source of the validation error. OpenAPI validation
            errors will set this to the expected value behavior (i.e the max length, or pattern).
          oneOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
              items: {}
            - type: object
          example: []
        field:
          description: "Field path, when the error is associated with a specific field."
          example: "applicant.dob"
          nullable: true
          type: string
      additionalProperties: false
